AllCops:
  Exclude:
    - db/**/*
    - bundle_bin/**/*
    - spec/**/*
    - bin/**/*
  Include:
    - exe/list_resolver
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Guardfile"
Layout/DotPosition:
  EnforcedStyle: trailing
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 35
Metrics/AbcSize:
  Max: 20
