AllCops:
  Exclude:
    - db/**/*
    - bundle_bin/**/*
    - spec/**/*
  Include:
    - exe/list_resolver
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/DotPosition:
  EnforcedStyle: trailing
Metrics/AbcSize:
  Max: 16
